### ISSUE TITLE
About performance degradation in cifar10

### ISSUE THREAD

**Issue by WuTi0525** [zhouchenlin2096/Spikingformer#3]
@zhouchenlin2096 
I only modified the path of the source code dataset you provided, but left the rest intact. I trained and tested the accuracy of the dataset cifar10. The default structure should be Spikingformer-4-384, I trained 400 epochs, and the highest accuracy was 95.17% in 310 epochs. 0.44% lower than reported in your paper (95.61%), Spikingformer-384-400E accuracy is 95.69%, 0.12% lower than reported in your paper (95.81%). It seems that these indicators are not very different, but for this task, such a small difference in accuracy can not be ignored, please help me to point out the possible reasons. In addition, the backend we use is CuPY and no changes have been made to the backend, torch version 2.1.0 and CUDA version 12.0, because CUDA version is higher and it restricts the use of the lower version of torch required in the source code.

**Comment by zhouchenlin2096** [comment]
1、Note that Spikingformer-4-384 (95.61%) and Spikingformer-4-384-400E (95.81%) are two independent experiments, setting epochs in cifar10.yml by 300 and 400 respectively. 
2、The decrease of 0.12% is within reasonable error range from my perspective and is mainly caused by initialization, data arguments, and even different GPUs. It is suggested to take the average for several times of training experiments.
3、It is suggested to try other datasets (such as cifar100 and imagenet) with better differentiation. In addition, welcome to try the latest improved version: https://github.com/zhouchenlin2096/Spikingformer-CML

**Comment by WuTi0525** [comment]
@zhouchenlin2096 Okay, thanks for your reply. I conducted the following experiment again according to your suggestion and obtained the following results:
Cifar10:
Spikingformer-4-384:95.46% (-0.15%)
Spikingformer-4-384E: 95.69% (-0.12%)
Cifar100:
Spikingformer-4-384: 78.95% (-0.14%)
Spikingformer-4-384E: 79.3% (+0.09%)
These performance differences are acceptable. Additionally, while reading your paper, I did not find any specific reasons why the Spikingformer outperforms than the Spikformer. Can you tell me the possible reasons for the performance improvement?

**Comment by zhouchenlin2096** [comment]
You can read some related papers like MS-resnet, Spike-driven transformer and our discussion part "Further Analysis for Last Layer" in our paper. Actually, I mainly proved that our residual connection is more energy-efficient, but can not confirm that our residual connection aways work better than SEW ADD in performance.
